export const TOYS_VEICOLI = [
  {
    id: 'hot-wheels-redline-twin-mill-1969',
    name: 'Hot Wheels Redline Twin Mill',
    brand: 'Mattel',
    line: 'Hot Wheels Redline',
    year: 1969,
    category: 'veicoli',
    country: 'USA',
    description: 'La Twin Mill è una delle auto più iconiche della linea Redline originale di Hot Wheels, lanciata nel 1969. Caratterizzata da due motori V8 sporgenti dal cofano, è diventata un simbolo della cultura hot rod americana. Le versioni originali con le ruote Redline sono oggi tra i pezzi più ricercati dai collezionisti.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-redline-custom-camaro-1968',
    name: 'Hot Wheels Redline Custom Camaro',
    brand: 'Mattel',
    line: 'Hot Wheels Redline',
    year: 1968,
    category: 'veicoli',
    country: 'USA',
    description: 'La Custom Camaro fu una delle sedici "Sweet Sixteen" originali lanciate nel 1968, le primissime Hot Wheels in assoluto. Con le caratteristiche ruote Redline a basso attrito, rivoluzionò il mercato delle miniature. Gli esemplari in colorazioni rare come il rosa o il viola possono valere migliaia di dollari.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-treasure-hunt-1995',
    name: 'Hot Wheels Treasure Hunt Series',
    brand: 'Mattel',
    line: 'Hot Wheels Treasure Hunt',
    year: 1995,
    category: 'veicoli',
    country: 'USA',
    description: 'La serie Treasure Hunt fu introdotta nel 1995 con una tiratura limitata di soli 10.000 pezzi per modello, rendendole immediatamente oggetto di caccia da parte dei collezionisti. Ogni veicolo presentava finiture speciali e verniciature metalliche esclusive. La serie creò un vero fenomeno di hunting nei negozi di giocattoli di tutto il mondo.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-criss-cross-crash-1992',
    name: 'Hot Wheels Criss Cross Crash',
    brand: 'Mattel',
    line: 'Hot Wheels Track Sets',
    year: 1992,
    category: 'veicoli',
    country: 'USA',
    description: 'Il Criss Cross Crash è uno dei playset di piste Hot Wheels più venduti e longevi della storia. Con il suo incrocio a quattro vie motorizzato, le auto si scontrano in modo spettacolare e imprevedibile. Il set è stato riproposto in numerose varianti nel corso degli anni, diventando un classico intramontabile.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-super-charger-1970',
    name: 'Hot Wheels Super Charger',
    brand: 'Mattel',
    line: 'Hot Wheels Track Accessories',
    year: 1970,
    category: 'veicoli',
    country: 'USA',
    description: 'Il Super Charger fu uno dei primi accessori motorizzati per le piste Hot Wheels, capace di lanciare le auto a velocità impressionanti. Alimentato a batterie, utilizzava due ruote rotanti per accelerare i veicoli lungo la pista arancione. Divenne un componente essenziale per ogni configurazione di pista Hot Wheels degli anni 70 e 80.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-loop-track-1985',
    name: 'Hot Wheels Loop & Speed Track',
    brand: 'Mattel',
    line: 'Hot Wheels Track Sets',
    year: 1985,
    category: 'veicoli',
    country: 'USA',
    description: 'I loop tracks di Hot Wheels permettevano alle auto di compiere giri della morte completi grazie alla forza centrifuga e alla gravità. La sfida era trovare la giusta velocità di lancio per completare il loop senza cadere. Questi set divennero un must-have per ogni bambino degli anni 80 e 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-monster-trucks-1991',
    name: 'Hot Wheels Monster Trucks',
    brand: 'Mattel',
    line: 'Hot Wheels Monster Trucks',
    year: 1991,
    category: 'veicoli',
    country: 'USA',
    description: 'I Monster Trucks Hot Wheels replicavano i giganteschi veicoli da arena con pneumatici oversize e sospensioni funzionanti. Modelli come Bigfoot e Snake Bite erano tra i più popolari, capaci di schiacciare le auto normali sotto le loro ruote enormi. La linea sfruttava il boom dei monster truck show americani degli anni 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'matchbox-superfast-1969',
    name: 'Matchbox Superfast Series',
    brand: 'Lesney / Matchbox',
    line: 'Superfast',
    year: 1969,
    category: 'veicoli',
    country: 'UK',
    description: 'La serie Superfast fu la risposta di Matchbox al lancio delle Hot Wheels, introducendo ruote a basso attrito che permettevano velocità molto superiori alle precedenti. Introdotta nel 1969, ridisegnò l\'intera gamma Matchbox mantenendo il realismo tipico del marchio britannico. I modelli Superfast degli anni 70 sono oggi molto ricercati.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'matchbox-classic-london-bus-1954',
    name: 'Matchbox London Bus No.5',
    brand: 'Lesney / Matchbox',
    line: 'Matchbox 1-75',
    year: 1954,
    category: 'veicoli',
    country: 'UK',
    description: 'Il London Bus rosso a due piani è uno dei modelli più iconici della storia Matchbox, prodotto in innumerevoli varianti dal 1954. Venduto nella celebre scatolina che dava il nome al marchio, rappresentava perfettamente lo spirito britannico del brand. Le prime versioni in metallo pressofuso sono oggi pezzi da collezione di grande valore.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'micro-machines-original-1987',
    name: 'Micro Machines Original Collection',
    brand: 'Galoob',
    line: 'Micro Machines',
    year: 1987,
    category: 'veicoli',
    country: 'USA',
    description: 'I Micro Machines furono lanciati da Galoob nel 1987 e divennero un fenomeno globale grazie alle loro dimensioni minuscole e ai prezzi accessibili. La pubblicità con John Moschitta Jr., l\'uomo che parlava più veloce del mondo, è rimasta leggendaria. I set tascabili che si aprivano rivelando intere città in miniatura erano geniali.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'micro-machines-star-wars-1994',
    name: 'Micro Machines Star Wars',
    brand: 'Galoob',
    line: 'Star Wars Micro Machines',
    year: 1994,
    category: 'veicoli',
    country: 'USA',
    description: 'La linea Star Wars Micro Machines portò le astronavi e i veicoli della saga di George Lucas in formato tascabile. I set includevano il Millennium Falcon, gli X-Wing, lo Star Destroyer e i veicoli imperiali con un livello di dettaglio sorprendente per le dimensioni. Le teste di personaggio che si aprivano rivelando playset erano particolarmente popolari.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'micro-machines-military-1989',
    name: 'Micro Machines Military Collection',
    brand: 'Galoob',
    line: 'Micro Machines Military',
    year: 1989,
    category: 'veicoli',
    country: 'USA',
    description: 'La serie Military dei Micro Machines includeva carri armati, elicotteri, navi da guerra e veicoli militari in scala ridottissima. Ogni set tematico rappresentava diversi eserciti e conflitti storici con sorprendente accuratezza. I playset militari che si aprivano da contenitori camuffati erano tra i più venduti della linea.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'micro-machines-city-playset-1991',
    name: 'Micro Machines Super City Playset',
    brand: 'Galoob',
    line: 'Micro Machines Cities',
    year: 1991,
    category: 'veicoli',
    country: 'USA',
    description: 'I playset città dei Micro Machines trasformavano oggetti quotidiani in intere città in miniatura, con strade, edifici e aree di gioco. La Super City era il set più grande e ambizioso, con più livelli collegati da rampe e strade. Questi playset rappresentavano il concetto di gioco portatile prima dell\'era digitale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-ferrari-f40-1987',
    name: 'Bburago Ferrari F40',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1987,
    category: 'veicoli',
    country: 'Italia',
    description: 'Il modello Bburago della Ferrari F40 in scala 1:18 è stato uno dei modellini più venduti nella storia dell\'azienda di Burago di Molgora. Riproduceva fedelmente l\'ultima Ferrari approvata personalmente da Enzo Ferrari, con porte apribili e dettagli del motore visibili. Era il sogno di ogni bambino italiano degli anni 80 e 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-ferrari-testarossa-1984',
    name: 'Bburago Ferrari Testarossa',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1984,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Ferrari Testarossa di Bburago, con il suo iconico design Pininfarina e le prese d\'aria laterali, era il modellino più desiderato degli anni 80. Resa famosa anche dalla serie TV Miami Vice, la Testarossa incarnava il lusso e la potenza italiana. Il modello 1:18 aveva cofano e porte apribili con interni dettagliati.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-lamborghini-countach-1988',
    name: 'Bburago Lamborghini Countach',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1988,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Lamborghini Countach di Bburago era il modellino che ogni ragazzino aveva sul comodino o sulla scrivania. Con le sue porte ad apertura verticale a forbice perfettamente funzionanti e il design futuristico, rappresentava il non plus ultra delle supercar. Il modello in scala 1:18 in metallo pressofuso pesava quasi come un\'auto vera in miniatura.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-lamborghini-diablo-1990',
    name: 'Bburago Lamborghini Diablo',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1990,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Lamborghini Diablo sostituì la Countach nel 1990 come ammiraglia del Toro, e Bburago ne realizzò subito un fedele modello in scala 1:18. Con il suo motore V12 da 485 CV, la Diablo era la prima Lamborghini a superare i 320 km/h. Il modellino in rosso o giallo era immancabile nelle collezioni dei ragazzi degli anni 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-porsche-911-turbo-1985',
    name: 'Bburago Porsche 911 Turbo',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1985,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Porsche 911 Turbo di Bburago riproduceva la leggendaria sportiva tedesca con il caratteristico alettone posteriore whale tail. Il modello in scala 1:18 presentava dettagli accurati del motore boxer a sei cilindri e interni ben rifiniti. Era spesso il primo pezzo di una collezione Bburago che poi cresceva nel tempo.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bburago-mercedes-300sl-1986',
    name: 'Bburago Mercedes-Benz 300 SL Gullwing',
    brand: 'Bburago',
    line: 'Bburago 1:18',
    year: 1986,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Mercedes 300 SL con le celebri porte ad ali di gabbiano era uno dei modelli più eleganti del catalogo Bburago. Riproduceva la leggendaria auto sportiva degli anni 50, considerata una delle più belle mai costruite. Le porte funzionanti che si aprivano verso l\'alto rendevano questo modellino particolarmente affascinante per grandi e piccoli.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polistil-ferrari-f1-1980',
    name: 'Polistil Ferrari Formula 1',
    brand: 'Polistil',
    line: 'Polistil Formula 1',
    year: 1980,
    category: 'veicoli',
    country: 'Italia',
    description: 'Le monoposto di Formula 1 Polistil erano il vanto dell\'industria italiana del giocattolo, con riproduzioni fedeli delle Ferrari da Gran Premio. L\'azienda milanese produceva modelli in diverse scale con livree aggiornate stagione per stagione. Per i tifosi della Rossa, possedere la Ferrari F1 Polistil di Villeneuve o Lauda era un must assoluto.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polistil-lancia-rally-1983',
    name: 'Polistil Lancia Rally 037',
    brand: 'Polistil',
    line: 'Polistil Rally',
    year: 1983,
    category: 'veicoli',
    country: 'Italia',
    description: 'La Lancia Rally 037 di Polistil celebrava la leggendaria auto che vinse il Campionato Mondiale Rally nel 1983, ultima vettura a trazione posteriore a riuscirci. Il modello riproduceva la livrea Martini Racing con grande fedeltà e dettagli accurati. Polistil era particolarmente forte nelle riproduzioni di auto da rally italiane.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polistil-pista-elettrica-champion-1982',
    name: 'Polistil Champion Pista Elettrica',
    brand: 'Polistil',
    line: 'Polistil Champion',
    year: 1982,
    category: 'veicoli',
    country: 'Italia',
    description: 'La pista elettrica Polistil Champion era il sogno di ogni bambino italiano degli anni 80. Con le sue auto slot car alimentate elettricamente e i tracciati componibili, permetteva sfide testa a testa tra amici e fratelli. I modelli di Formula 1 e GT sfrecciavano nelle curve paraboliche a velocità regolabile tramite il controller manuale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'majorette-serie-200-1980',
    name: 'Majorette Serie 200',
    brand: 'Majorette',
    line: 'Serie 200',
    year: 1980,
    category: 'veicoli',
    country: 'Francia',
    description: 'Le Majorette Serie 200 erano le macchinine francesi che competevano con Hot Wheels e Matchbox, offrendo un ottimo rapporto qualità-prezzo. La gamma includeva centinaia di modelli di auto, camion e veicoli speciali in scala circa 1:64. Con le loro ruote veloci e la robustezza del metallo pressofuso, erano perfette per il gioco quotidiano.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'majorette-pompieri-range-rover-1985',
    name: 'Majorette Range Rover Pompieri',
    brand: 'Majorette',
    line: 'Serie 200 Emergency',
    year: 1985,
    category: 'veicoli',
    country: 'Francia',
    description: 'Il Range Rover dei pompieri Majorette era uno dei modelli più amati della linea veicoli di emergenza. Con la livrea rossa fiammante, la scala funzionante e i dettagli realistici, era un classico intramontabile. Majorette eccelleva nella produzione di veicoli di servizio, dai pompieri alla polizia fino alle ambulanze.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tamiya-mini-4wd-magnum-saber-1994',
    name: 'Tamiya Mini 4WD Magnum Saber',
    brand: 'Tamiya',
    line: 'Mini 4WD',
    year: 1994,
    category: 'veicoli',
    country: 'Giappone',
    description: 'Il Magnum Saber era una delle Mini 4WD più iconiche di Tamiya, reso famoso dal manga e anime "Bakusou Kyoudai Let\'s & Go!!". Con il suo design aerodinamico e il telaio Super-1, era la base perfetta per personalizzazioni e potenziamenti. Le gare di Mini 4WD nei negozi di modellismo erano un evento sociale per i ragazzi degli anni 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tamiya-mini-4wd-sonic-saber-1996',
    name: 'Tamiya Mini 4WD Sonic Saber',
    brand: 'Tamiya',
    line: 'Mini 4WD',
    year: 1996,
    category: 'veicoli',
    country: 'Giappone',
    description: 'Il Sonic Saber era l\'evoluzione del Magnum Saber, con un design ancora più aerodinamico e prestazioni superiori. Equipaggiato con il telaio Super-TZ, offriva maggiore stabilità nelle curve ad alta velocità. Come il suo predecessore, era protagonista dell\'anime Let\'s & Go!! e catalizzava l\'attenzione dei giovani appassionati di modellismo.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tamiya-mini-4wd-avante-jr-1988',
    name: 'Tamiya Mini 4WD Avante Jr.',
    brand: 'Tamiya',
    line: 'Mini 4WD Racing',
    year: 1988,
    category: 'veicoli',
    country: 'Giappone',
    description: 'L\'Avante Jr. fu una delle prime Mini 4WD di Tamiya a raggiungere grande popolarità, basata sul celebre buggy RC Avante in scala 1:10. Con il telaio Type-2 e il motore Mabuchi, era un perfetto equilibrio tra velocità e maneggevolezza. Rappresentò l\'inizio della mania delle Mini 4WD che avrebbe conquistato l\'Asia e l\'Europa.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'scalextric-pista-1980',
    name: 'Scalextric Pista Slot Car',
    brand: 'Hornby / Scalextric',
    line: 'Scalextric',
    year: 1980,
    category: 'veicoli',
    country: 'UK',
    description: 'Scalextric è il marchio britannico di piste slot car più famoso al mondo, con una tradizione che risale al 1957. Le auto in scala 1:32 corrono su binari elettrificati controllate da pistole analogiche che regolano la velocità. Negli anni 80 e 90 i set con auto di Formula 1 e Le Mans erano i regali di Natale più desiderati.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'carrera-pista-slot-1985',
    name: 'Carrera Slot Racing',
    brand: 'Carrera',
    line: 'Carrera Universal',
    year: 1985,
    category: 'veicoli',
    country: 'Germania',
    description: 'Le piste Carrera, prodotte dall\'azienda tedesca Stadlbauer, erano sinonimo di qualità e precisione ingegneristica germanica. Il sistema Universal in scala 1:32 offriva tracciati modulari espandibili con curve sopraelevate e rettilinei ad alta velocità. La rivalità con Scalextric e Polistil Champion animava il mercato europeo delle slot car.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tonka-mighty-dump-truck-1983',
    name: 'Tonka Mighty Dump Truck',
    brand: 'Tonka',
    line: 'Mighty Tonka',
    year: 1983,
    category: 'veicoli',
    country: 'USA',
    description: 'Il Mighty Dump Truck giallo di Tonka era costruito in acciaio pressato e praticamente indistruttibile, perfetto per il gioco all\'aperto. Con il suo cassone ribaltabile funzionante, era il compagno ideale per giocare nella sabbia e nel fango. Dal 1965 Tonka produceva camion gialli che sono diventati un\'icona del giocattolo americano.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tonka-mighty-crane-1985',
    name: 'Tonka Mighty Crane',
    brand: 'Tonka',
    line: 'Mighty Tonka',
    year: 1985,
    category: 'veicoli',
    country: 'USA',
    description: 'La gru Tonka Mighty Crane era un capolavoro di robustezza con braccio girevole e cavo funzionante per sollevare carichi. Come tutti i Mighty Tonka, era realizzata in resistente acciaio verniciato di giallo, capace di resistere ad anni di gioco intenso. Insieme al Dump Truck formava il cantiere perfetto per ogni piccolo costruttore.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'gig-nikko-rc-turbo-panther-1988',
    name: 'GIG Nikko RC Turbo Panther',
    brand: 'GIG / Nikko',
    line: 'Nikko RC',
    year: 1988,
    category: 'veicoli',
    country: 'Italia / Giappone',
    description: 'La Turbo Panther di Nikko, distribuita in Italia da GIG, era l\'auto radiocomandata che tutti i bambini italiani desideravano. Con la sua velocità impressionante e la capacità di affrontare ogni terreno, era protagonista di infinite gare nei cortili e nei parchi. Le pubblicità GIG Nikko durante i cartoni animati erano irresistibili.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'gig-nikko-rc-savage-1992',
    name: 'GIG Nikko RC Savage',
    brand: 'GIG / Nikko',
    line: 'Nikko RC Off-Road',
    year: 1992,
    category: 'veicoli',
    country: 'Italia / Giappone',
    description: 'Il Nikko Savage era un buggy radiocomandato off-road che dominava il mercato italiano delle RC car negli anni 90. Con le sue sospensioni robuste e i pneumatici tassellati, affrontava sterrato, erba e ghiaia senza problemi. GIG lo pubblicizzava massicciamente in TV, rendendolo uno dei giocattoli più richiesti a Natale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tyco-rc-rebound-1994',
    name: 'Tyco RC Rebound 4x4',
    brand: 'Tyco',
    line: 'Tyco RC',
    year: 1994,
    category: 'veicoli',
    country: 'USA',
    description: 'Il Tyco Rebound 4x4 era rivoluzionario: quando si ribaltava, continuava a correre grazie al suo design simmetrico con ruote su entrambi i lati. Questa caratteristica unica lo rendeva praticamente inarrestabile su qualsiasi terreno e in qualsiasi situazione. Fu uno dei giocattoli radiocomandati più innovativi e venduti degli anni 90.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'tyco-rc-mutator-1997',
    name: 'Tyco RC Mutator',
    brand: 'Tyco',
    line: 'Tyco RC Xtreme',
    year: 1997,
    category: 'veicoli',
    country: 'USA',
    description: 'Il Tyco Mutator era un veicolo radiocomandato che poteva trasformarsi durante la corsa, cambiando assetto e stile di guida. Con la sua estetica aggressiva e le prestazioni elevate, competeva direttamente con i Nikko distribuiti da GIG. Le auto RC Tyco erano note per la qualità dei motori e la durata delle batterie.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'maisto-ferrari-550-maranello-1998',
    name: 'Maisto Ferrari 550 Maranello',
    brand: 'Maisto',
    line: 'Maisto Special Edition 1:18',
    year: 1998,
    category: 'veicoli',
    country: 'USA / Thailandia',
    description: 'Maisto si affermò negli anni 90 come alternativa più economica a Bburago per i modellini in scala 1:18, con la Ferrari 550 Maranello tra i suoi pezzi più riusciti. Il livello di dettaglio era notevole per il prezzo contenuto, con porte, cofano e bagagliaio apribili. Maisto contribuì a democratizzare il collezionismo di auto in scala.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'maisto-dodge-viper-gts-1996',
    name: 'Maisto Dodge Viper GTS',
    brand: 'Maisto',
    line: 'Maisto Special Edition 1:18',
    year: 1996,
    category: 'veicoli',
    country: 'USA / Thailandia',
    description: 'La Dodge Viper GTS blu con strisce bianche di Maisto era uno dei modelli americani più popolari della gamma Special Edition. Con il suo enorme motore V10 da 8 litri fedelmente riprodotto sotto il cofano apribile, incarnava la muscle car americana per eccellenza. Era spesso il primo modellino non europeo nelle collezioni italiane.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'matchbox-land-rover-defender-1993',
    name: 'Matchbox Land Rover Defender 110',
    brand: 'Matchbox',
    line: 'Matchbox Superfast',
    year: 1993,
    category: 'veicoli',
    country: 'UK',
    description: 'Il Land Rover Defender 110 di Matchbox era uno dei modelli fuoristrada più realistici della gamma anni 90. Matchbox si distingueva da Hot Wheels per il maggiore realismo delle proporzioni e dei dettagli, privilegiando veicoli reali rispetto a design fantasy. Il Defender in verde militare era particolarmente ricercato dai piccoli avventurieri.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'hot-wheels-ferrari-f50-1995',
    name: 'Hot Wheels Ferrari F50',
    brand: 'Mattel',
    line: 'Hot Wheels Mainline',
    year: 1995,
    category: 'veicoli',
    country: 'USA',
    description: 'La Ferrari F50 di Hot Wheels celebrava il cinquantesimo anniversario della casa di Maranello con una delle supercar più esclusive mai prodotte. Il modellino in scala 1:64 riproduceva le linee sinuose disegnate da Pininfarina con la tipica qualità Hot Wheels. Era uno dei modelli più contesi nelle edicole e nei negozi di giocattoli italiani.',
    image: null,
    aiGenerated: true,
  },
];
