export const TOYS_BAMBOLE = [
  {
    id: 'barbie-malibu-1981',
    name: 'Barbie Malibu',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1981,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Malibu è stata una delle versioni più iconiche della bambola, con il suo sorriso abbronzato e il costume da bagno azzurro. Lanciata originariamente nel 1971, la versione anni 80 ha consolidato il mito della Barbie californiana amante della spiaggia.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-western-1982',
    name: 'Barbie Western',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1982,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Western cavalcava il suo cavallo Dallas vestita con stivali, cappello da cowgirl e gilet con frange. Rappresentava lo spirito avventuroso del Far West e includeva accessori a tema country.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-astronaut-1985',
    name: 'Barbie Astronaut',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1985,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Astronauta indossava una tuta spaziale rosa e argento completa di casco trasparente. Ispirata alla corsa allo spazio, Mattel voleva dimostrare che Barbie poteva fare qualsiasi mestiere, incluso esplorare le stelle.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-doctor-1988',
    name: 'Barbie Doctor',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1988,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Dottoressa arrivava con camice bianco, stetoscopio e valigetta medica. Faceva parte della serie carriere di Barbie, pensata per ispirare le bambine a sognare professioni ambiziose.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-totally-hair-1992',
    name: 'Barbie Totally Hair',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1992,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Totally Hair è la Barbie più venduta di tutti i tempi con oltre 10 milioni di esemplari. Aveva capelli lunghissimi fino ai piedi e veniva fornita con gel per lo styling in colori vivaci.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-holiday-1994',
    name: 'Holiday Barbie',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1994,
    category: 'bambole',
    country: 'USA',
    description: 'La Holiday Barbie era una edizione speciale natalizia da collezione, vestita con un elegante abito dorato e rosso. La serie Happy Holidays, iniziata nel 1988, è diventata un appuntamento annuale per i collezionisti di tutto il mondo.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-president-2000',
    name: 'Barbie President',
    brand: 'Mattel',
    line: 'Barbie',
    year: 2000,
    category: 'bambole',
    country: 'USA',
    description: 'La Barbie Presidente indossava un tailleur blu presidenziale e rappresentava la possibilità per le donne di raggiungere la più alta carica politica. Una bambola pensata per ispirare leadership e ambizione nelle bambine.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-rapunzel-2002',
    name: 'Barbie Rapunzel',
    brand: 'Mattel',
    line: 'Barbie',
    year: 2002,
    category: 'bambole',
    country: 'USA',
    description: 'Barbie Rapunzel era ispirata al film d\'animazione omonimo di Mattel. La bambola aveva lunghissimi capelli biondi con pennello magico e un abito da principessa rosa e lilla con dettagli glitterati.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-e-ken-1985',
    name: 'Barbie e Ken',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1985,
    category: 'bambole',
    country: 'USA',
    description: 'La coppia più famosa del mondo delle bambole, Barbie e Ken erano venduti spesso in confezioni regalo insieme. Ken, introdotto nel 1961, è sempre stato il fidanzato perfetto di Barbie in innumerevoli versioni tematiche.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-fashionistas-2005',
    name: 'Barbie Fashionistas',
    brand: 'Mattel',
    line: 'Barbie',
    year: 2005,
    category: 'bambole',
    country: 'USA',
    description: 'Le Barbie Fashionistas portavano la moda contemporanea nel mondo delle bambole con outfit alla moda e accessori trendy. Ogni bambola aveva un look unico e personalità distinte, aprendo la strada alla diversità della linea moderna.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'barbie-dream-house-1990',
    name: 'Barbie Dream House',
    brand: 'Mattel',
    line: 'Barbie',
    year: 1990,
    category: 'bambole',
    country: 'USA',
    description: 'La Dream House degli anni 90 era una casa dei sogni rosa a tre piani con ascensore funzionante, piscina e garage. La Casa dei Sogni di Barbie è stata reinventata più volte dal 1962, diventando il playset più desiderato dalle bambine.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'cicciobello-1983',
    name: 'Cicciobello',
    brand: 'Giochi Preziosi / Sebino',
    line: 'Cicciobello',
    year: 1983,
    category: 'bambole',
    country: 'Italia',
    description: 'Cicciobello è il bambolotto più amato d\'Italia, con il suo visino paffuto e gli occhi azzurri. Creato da Sebino negli anni 60 e poi prodotto da Giochi Preziosi, generazioni di bambini italiani hanno imparato a prendersi cura di un bebè giocando con lui.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'cicciobello-bua-1995',
    name: 'Cicciobello Bua',
    brand: 'Giochi Preziosi',
    line: 'Cicciobello',
    year: 1995,
    category: 'bambole',
    country: 'Italia',
    description: 'Cicciobello Bua è la versione interattiva che piange quando sta male e guarisce con le coccole. Aveva macchie rosse sul corpo che scomparivano con l\'acqua fredda, simulando la guarigione del bambolotto malato.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'cicciobello-sunny-2003',
    name: 'Cicciobello Sunny',
    brand: 'Giochi Preziosi',
    line: 'Cicciobello',
    year: 2003,
    category: 'bambole',
    country: 'Italia',
    description: 'Cicciobello Sunny era la versione estiva del celebre bambolotto, che si abbronzava al sole grazie a una tecnologia UV-reattiva. Portandolo all\'aperto la sua pelle cambiava colore, tornando chiara una volta rientrato in casa.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'cabbage-patch-kids-1983',
    name: 'Cabbage Patch Kids / Bamboli Verza',
    brand: 'Coleco / Mattel',
    line: 'Cabbage Patch Kids',
    year: 1983,
    category: 'bambole',
    country: 'USA',
    description: 'I Cabbage Patch Kids, noti in Italia come Bamboli Verza, erano bambole morbide con faccine rotonde e un certificato di adozione unico. Nel 1983 scatenarono una vera follia natalizia negli USA con risse nei negozi per accaparrarseli.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'my-little-pony-g1-1983',
    name: 'My Little Pony G1',
    brand: 'Hasbro',
    line: 'My Little Pony',
    year: 1983,
    category: 'bambole',
    country: 'USA',
    description: 'I My Little Pony di prima generazione erano piccoli cavallini colorati con criniere pettinabili e un simbolo unico sul fianco chiamato cutie mark. Lanciati da Hasbro nel 1983, hanno generato una serie animata e un universo di accessori e playsets.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'my-little-pony-g3-2003',
    name: 'My Little Pony G3',
    brand: 'Hasbro',
    line: 'My Little Pony',
    year: 2003,
    category: 'bambole',
    country: 'USA',
    description: 'La terza generazione dei My Little Pony presentava un design più rotondo e tenero rispetto ai predecessori. I pony G3 avevano pose diverse e accessori glitterati, accompagnati da speciali DVD con animazioni in CGI.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sailor-moon-doll-1993',
    name: 'Sailor Moon Doll',
    brand: 'Bandai / Giochi Preziosi',
    line: 'Sailor Moon',
    year: 1993,
    category: 'bambole',
    country: 'Giappone',
    description: 'La bambola di Sailor Moon rappresentava Usagi Tsukino nella sua trasformazione da guerriera lunare con il tipico costume alla marinara bianco e blu. In Italia il fenomeno Sailor Moon esplose a metà anni 90 con le bambole distribuite da Giochi Preziosi.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sailor-mercury-doll-1994',
    name: 'Sailor Mercury Doll',
    brand: 'Bandai / Giochi Preziosi',
    line: 'Sailor Moon',
    year: 1994,
    category: 'bambole',
    country: 'Giappone',
    description: 'La bambola di Sailor Mercury rappresentava Ami Mizuno, la guerriera dell\'acqua con i capelli blu corti. Era la più studiosa del gruppo e la sua bambola indossava il costume alla marinara azzurro con fiocco celeste.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sailor-mars-doll-1994',
    name: 'Sailor Mars Doll',
    brand: 'Bandai / Giochi Preziosi',
    line: 'Sailor Moon',
    year: 1994,
    category: 'bambole',
    country: 'Giappone',
    description: 'La bambola di Sailor Mars rappresentava Rei Hino, la guerriera del fuoco con i lunghi capelli neri. Il suo costume alla marinara rosso e viola la rendeva una delle bambole più ricercate della collezione.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sailor-jupiter-doll-1994',
    name: 'Sailor Jupiter Doll',
    brand: 'Bandai / Giochi Preziosi',
    line: 'Sailor Moon',
    year: 1994,
    category: 'bambole',
    country: 'Giappone',
    description: 'La bambola di Sailor Jupiter rappresentava Makoto Kino, la guerriera del tuono alta e forte. Con il suo costume verde e la coda di cavallo, era la combattente più fisica del gruppo delle Sailor Senshi.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sailor-venus-doll-1994',
    name: 'Sailor Venus Doll',
    brand: 'Bandai / Giochi Preziosi',
    line: 'Sailor Moon',
    year: 1994,
    category: 'bambole',
    country: 'Giappone',
    description: 'La bambola di Sailor Venus rappresentava Minako Aino, la guerriera dell\'amore con il fiocco rosso tra i capelli biondi. Era stata la prima Sailor Senshi a risvegliarsi e la sua bambola indossava il costume arancione.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polly-pocket-original-compact-1989',
    name: 'Polly Pocket Original Compact',
    brand: 'Bluebird Toys',
    line: 'Polly Pocket',
    year: 1989,
    category: 'bambole',
    country: 'UK',
    description: 'Le Polly Pocket originali erano minuscole bamboline di circa 2 cm contenute in portacipria colorati apribili. Inventate da Chris Wiggs per sua figlia nel 1983, furono commercializzate da Bluebird Toys e divennero un fenomeno globale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polly-pocket-casa-1991',
    name: 'Polly Pocket Casa',
    brand: 'Bluebird Toys',
    line: 'Polly Pocket',
    year: 1991,
    category: 'bambole',
    country: 'UK',
    description: 'La Polly Pocket Casa era uno dei playset più amati, un compact a forma di casetta che si apriva rivelando stanze arredate in miniatura. Le tiny dolls si incastravano nei piedistalli per giocare nelle varie ambientazioni.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polly-pocket-castello-1995',
    name: 'Polly Pocket Castello',
    brand: 'Bluebird Toys',
    line: 'Polly Pocket',
    year: 1995,
    category: 'bambole',
    country: 'UK',
    description: 'Il Castello di Polly Pocket era un playset più grande con torri, ponte levatoio e stanze da principessa. Rappresentava l\'evoluzione della linea verso set più elaborati mantenendo il fascino delle minuscole bamboline.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'polly-pocket-piscina-1993',
    name: 'Polly Pocket Piscina',
    brand: 'Bluebird Toys',
    line: 'Polly Pocket',
    year: 1993,
    category: 'bambole',
    country: 'UK',
    description: 'La Polly Pocket Piscina era un compact a tema estivo con scivolo e zona relax per le micro bamboline. I compact acquatici erano tra i più divertenti perché univano il gioco con l\'acqua alla portabilità tascabile.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bratz-cloe-2001',
    name: 'Bratz Cloe',
    brand: 'MGA Entertainment',
    line: 'Bratz',
    year: 2001,
    category: 'bambole',
    country: 'USA',
    description: 'Cloe, soprannominata Angel, era la bionda del gruppo Bratz con grandi occhi a mandorla e labbra carnose. Le Bratz rivoluzionarono il mercato delle fashion doll sfidando il dominio di Barbie con uno stile urban e multiculturale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bratz-jade-2001',
    name: 'Bratz Jade',
    brand: 'MGA Entertainment',
    line: 'Bratz',
    year: 2001,
    category: 'bambole',
    country: 'USA',
    description: 'Jade, soprannominata Kool Kat, era la Bratz di origine asiatica appassionata di moda e tendenze. Con i suoi capelli neri lisci e lo stile alternativo, rappresentava la diversità nel mondo delle bambole fashion.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bratz-sasha-2001',
    name: 'Bratz Sasha',
    brand: 'MGA Entertainment',
    line: 'Bratz',
    year: 2001,
    category: 'bambole',
    country: 'USA',
    description: 'Sasha, soprannominata Bunny Boo, era la Bratz afroamericana amante della musica hip-hop e dell\'urban style. Le sue scarpe intercambiabili con piedi removibili erano una caratteristica innovativa della linea Bratz.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'bratz-yasmin-2001',
    name: 'Bratz Yasmin',
    brand: 'MGA Entertainment',
    line: 'Bratz',
    year: 2001,
    category: 'bambole',
    country: 'USA',
    description: 'Yasmin, soprannominata Pretty Princess, era la Bratz latina con lunghi capelli castani ondulati. Considerata la leader del gruppo, incarnava uno stile boho-chic che la distingueva dalle altre bambole fashion dell\'epoca.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'strawberry-shortcake-1980',
    name: 'Strawberry Shortcake / Fragolina Dolcecuore',
    brand: 'Kenner',
    line: 'Strawberry Shortcake',
    year: 1980,
    category: 'bambole',
    country: 'USA',
    description: 'Fragolina Dolcecuore era una bambolina profumata alla fragola con il cappellino rosa e i capelli rossi. In Italia divenne popolarissima negli anni 80 con il nome italiano, insieme alle sue amiche Uvetta, Mandarancina e le altre.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'rainbow-brite-iridella-1984',
    name: 'Rainbow Brite / Iridella',
    brand: 'Mattel',
    line: 'Rainbow Brite',
    year: 1984,
    category: 'bambole',
    country: 'USA',
    description: 'Iridella era la bambina guerriera dell\'arcobaleno che proteggeva i colori del mondo con il suo cavallo Starlite. In Italia la serie animata e le bambole ebbero grande successo, con i personaggi dei Color Kids e gli Sprites.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'jem-and-the-holograms-1986',
    name: 'Jem and the Holograms',
    brand: 'Hasbro',
    line: 'Jem',
    year: 1986,
    category: 'bambole',
    country: 'USA',
    description: 'Jem era la bambola rock star con capelli rosa shocking e orecchini luminosi a forma di stella. Basata sulla serie animata, Jem si trasformava da Jerrica Benton in pop star grazie al computer olografico Synergy.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'baby-born-1991',
    name: 'Baby Born',
    brand: 'Zapf Creation',
    line: 'Baby Born',
    year: 1991,
    category: 'bambole',
    country: 'Germania',
    description: 'Baby Born era il bambolotto interattivo che poteva bere dal biberon, mangiare la pappa, piangere lacrime vere e fare la pipì nel vasino. Senza batterie, funzionava grazie a un meccanismo ad acqua che lo rendeva realistico e adatto ai più piccoli.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'baby-alive-1992',
    name: 'Baby Alive',
    brand: 'Kenner / Hasbro',
    line: 'Baby Alive',
    year: 1992,
    category: 'bambole',
    country: 'USA',
    description: 'Baby Alive era la bambola che mangiava davvero la sua pappa speciale e poi sporcava il pannolino. Originariamente lanciata nel 1973 da Kenner, fu riproposta negli anni 90 con versioni più moderne e funzioni interattive.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'trolls-capelli-colorati-1992',
    name: 'Trolls (Capelli Colorati)',
    brand: 'Russ Berrie / Dam Things',
    line: 'Trolls',
    year: 1992,
    category: 'bambole',
    country: 'Danimarca',
    description: 'I Troll con i capelli colorati sparati in su erano pupazzetti portafortuna creati dal danese Thomas Dam nel 1959. Negli anni 90 tornarono di moda in versioni fluorescenti con capelli rosa, verdi e arancioni, collezionati da milioni di bambini.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'winx-club-bloom-2004',
    name: 'Winx Club Bloom',
    brand: 'Giochi Preziosi / Rainbow',
    line: 'Winx Club',
    year: 2004,
    category: 'bambole',
    country: 'Italia',
    description: 'La bambola di Bloom, la fata del fuoco protagonista delle Winx Club, aveva capelli rosso-arancio e ali glitterate. Creata da Iginio Straffi e la Rainbow di Loreto, la serie animata italiana conquistò il mercato globale delle bambole fashion.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'winx-club-stella-2004',
    name: 'Winx Club Stella',
    brand: 'Giochi Preziosi / Rainbow',
    line: 'Winx Club',
    year: 2004,
    category: 'bambole',
    country: 'Italia',
    description: 'Stella, la fata del sole e della luna, era la fashionista del gruppo Winx con i suoi capelli biondi e l\'outfit arancione. La sua bambola era tra le più vendute della linea grazie alla sua personalità solare e glamour.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'winx-club-flora-2004',
    name: 'Winx Club Flora',
    brand: 'Giochi Preziosi / Rainbow',
    line: 'Winx Club',
    year: 2004,
    category: 'bambole',
    country: 'Italia',
    description: 'Flora, la fata della natura, era la più dolce e sensibile del gruppo Winx. La sua bambola aveva capelli castano chiaro e un vestito rosa e verde ispirato ai fiori e alla primavera.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'winx-club-musa-2004',
    name: 'Winx Club Musa',
    brand: 'Giochi Preziosi / Rainbow',
    line: 'Winx Club',
    year: 2004,
    category: 'bambole',
    country: 'Italia',
    description: 'Musa, la fata della musica, aveva i capelli neri con codini e un outfit rosso. La sua bambola rappresentava il personaggio di origine asiatica appassionato di musica e canto della serie Winx Club.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'winx-club-tecna-2004',
    name: 'Winx Club Tecna',
    brand: 'Giochi Preziosi / Rainbow',
    line: 'Winx Club',
    year: 2004,
    category: 'bambole',
    country: 'Italia',
    description: 'Tecna, la fata della tecnologia, era la più razionale e logica del gruppo. La sua bambola aveva capelli corti viola e un costume futuristico lilla, riflettendo la sua passione per computer e scienza.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'dora-esploratrice-2003',
    name: 'Dora l\'Esploratrice',
    brand: 'Fisher-Price / Mattel',
    line: 'Dora the Explorer',
    year: 2003,
    category: 'bambole',
    country: 'USA',
    description: 'La bambola di Dora l\'Esploratrice riproduceva la popolare protagonista del cartone Nickelodeon con la sua maglietta rosa e lo zaino viola parlante. Dora insegnava lo spagnolo e l\'inglese ai bambini attraverso avventure interattive.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'betty-spaghetti-1998',
    name: 'Betty Spaghetti',
    brand: 'Ohio Art / Giochi Preziosi',
    line: 'Betty Spaghetti',
    year: 1998,
    category: 'bambole',
    country: 'USA',
    description: 'Betty Spaghetti era una bambola flessibile con braccia, gambe e capelli fatti di plastica morbida a forma di spaghetti. Le parti del corpo erano intercambiabili tra le diverse bambole della serie, permettendo combinazioni creative.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'littlest-pet-shop-1992',
    name: 'Littlest Pet Shop',
    brand: 'Kenner / Hasbro',
    line: 'Littlest Pet Shop',
    year: 1992,
    category: 'bambole',
    country: 'USA',
    description: 'I Littlest Pet Shop erano animaletti in miniatura con teste grandi e occhi espressivi, accompagnati da playset a tema veterinario. Lanciati nel 1992 da Kenner, furono rilanciati con enorme successo da Hasbro nel 2005 con il design bobblehead.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'holly-hobbie-1980',
    name: 'Holly Hobbie',
    brand: 'Knickerbocker / Mattel',
    line: 'Holly Hobbie',
    year: 1980,
    category: 'bambole',
    country: 'USA',
    description: 'Holly Hobbie era una bambola di pezza ispirata all\'omonimo personaggio creato dall\'illustratrice americana Denise Holly Ulinskas Hobbie. Con il suo cappellone e il vestito patchwork in stile country, rappresentava i valori semplici della vita rurale.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'sylvanian-families-1985',
    name: 'Sylvanian Families',
    brand: 'Epoch',
    line: 'Sylvanian Families',
    year: 1985,
    category: 'bambole',
    country: 'Giappone',
    description: 'Le Sylvanian Families erano famiglie di animaletti floccati in miniatura che vivevano in case e negozi dettagliatissimi. Create dall\'azienda giapponese Epoch nel 1985, includevano conigli, orsi, ricci e tanti altri animali vestiti elegantemente.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'puppa-bambola-di-pezza-1980',
    name: 'Puppa / Bambola di Pezza',
    brand: 'Vari produttori artigianali',
    line: 'Bambole di pezza',
    year: 1980,
    category: 'bambole',
    country: 'Italia',
    description: 'La bambola di pezza o Puppa era un classico intramontabile realizzato artigianalmente in stoffa con capelli di lana e viso dipinto a mano. In Italia rappresentava la tradizione delle nonne che cucivano bambole per le nipoti con avanzi di tessuto.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'moncicci-1980',
    name: 'Monciccì',
    brand: 'Sekiguchi',
    line: 'Monchhichi',
    year: 1980,
    category: 'bambole',
    country: 'Giappone',
    description: 'I Monciccì erano pupazzetti scimmieschi con il viso in vinile e il corpo in peluche, famosi per il gesto di succhiarsi il pollice. Creati dall\'azienda giapponese Sekiguchi nel 1974, in Italia divennero un fenomeno degli anni 80 con il nome italianizzato.',
    image: null,
    aiGenerated: true,
  },
  {
    id: 'puffetta-smurfs-1982',
    name: 'Puffetta (Smurfs)',
    brand: 'Schleich / Peyo',
    line: 'I Puffi',
    year: 1982,
    category: 'bambole',
    country: 'Belgio',
    description: 'Puffetta era l\'unica femmina del villaggio dei Puffi, creata dal mago Gargamella e poi trasformata in buona da Grande Puffo. Le sue bambole e action figure, con i capelli biondi e il vestitino bianco, erano tra le più vendute della linea Puffi di Schleich.',
    image: null,
    aiGenerated: true,
  },
];
